name: Terraform

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
      TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_pgpassword_value: ${{ secrets.PGPASSWORD_VALUE }}
      TF_VAR_app_secret_value: ${{ secrets.APP_SECRET_VALUE }}
      TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}
      TF_VAR_db_sg_ids: ${{secrets.DB_SG_IDS}}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.2

      - name: Terraform Format
        run: terraform fmt -check -recursive infrastructure/environments/prod

      - name: Terraform Init
        run: terraform -chdir=infrastructure/environments/prod init

      - name: Terraform Validate
        run: terraform -chdir=infrastructure/environments/prod validate

      - name: Terraform Plan
        run: terraform -chdir=infrastructure/environments/prod plan -input=false
